name: Github Pages Deploy Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"  

      - run: npm ci

      - name: Build Project
        run: CI=false npm run build

      - name: Set up Git user
        run: |
          git config --global user.name 'Spencer'
          git config --global user.email 'sfd0014@auburn.edu'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build